server:
  port: 19093

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/msa_assignment
    username: postgres
    password: database123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

logging:
  level:
    org.springframework.web: DEBUG

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0