server:
  port: 19092


spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/msa_assignment
    username: postgres
    password: database123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/